#!/bin/bash
sshpass -p raspberry scp -r ./* pi@192.168.25.6:/home/pi/Documents/projetos/raspcpba-master_temp/
#sshpass -p raspberry scp -r ./* pi@192.168.2.103:/home/pi/Documents/projetos/raspcpba-master_temp/
# sshpass -p raspberry ssh pi@192.168.2.103 "cd /home/pi/Documents/projetos/raspcpba-master_temp; git pull origin master"
# sshpass -p raspberry ssh pi@192.168.2.103 "cd /home/pi/workspace/app/; echo 'raspberry' | sudo pip install -r requirements.txt; ./run"
